# Generated by Django 2.0 on 2017-12-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player to move'), ('S', 'Second player to move'), ('W', 'First player wins'), ('L', 'Second player wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
