# Generated by Django 2.0 on 2017-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20171219_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move_made_by_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
